project:
  type: website
  output-dir: docs
  render:
    - index.qmd

website:
  title: "Practical Image Processing for Manuscripts"

format:
  html:
    toc: true
    toc-depth: 3
    code-copy: true
    code-line-numbers: true
    code-overflow: wrap
    theme: cosmo
    highlight-style: github
    css: styles.css
    fig-cap-location: bottom

execute:
  eval: false
  echo: true
  freeze: auto
